In [12]:
from sklearn.cluster import KMeans
from PIL import Image
import numpy as np

In [13]:
def compress(Img_path,n_color):
    n_color=min(n_color,256*256)
    img=Image.open(Img_path)
    img=np.array(img)
    height, width, channels = img.shape
    shape=np.array([height,width,channels],dtype=np.int32)
    pixels = img.reshape(-1, channels)

    km=KMeans(n_clusters=n_color,init='k-means++',)
    km.fit(pixels)
    centroids=km.cluster_centers_
    centroids=centroids.astype(np.uint8)
    labels=km.labels_

    if n_color<257:
        labels=labels.astype(np.int8)
    else:
        labels=labels.astype(np.int16)
    
    np.savez_compressed(f"{Img_path.split('.')[0]}.npz",labels=labels,centroids=centroids,shape=shape)

In [67]:
compress(Img_path="image2.png",n_color=256)

In [68]:
def extract(img_path):
    img=np.load(img_path)
    labels,centroids,shape=img['labels'],img['centroids'],img['shape']
    print(centroids)
    extracted_img=np.empty((shape[0]*shape[1],shape[2]))
    for ind,label in enumerate(labels):
        extracted_img[ind]=centroids[label]
    extracted_img=extracted_img.reshape(shape)
    print(extracted_img.shape)
    extracted_img=extracted_img.astype(np.uint8)
    ex_img=Image.fromarray(extracted_img)
    ex_img.save("extracted.png")
    

In [69]:
extract("image2.npz")

[[165 128 166]
 [ 69  85 113]
 [ 53  31  63]
 [217 185 202]
 [126 106 151]
 [ 98 155 211]
 [ 97  96 140]
 [ 63  44  75]
 [ 79 123 178]
 [193 153 181]
 [143 193 234]
 [ 63  91 138]
 [ 62  64 101]
 [243 205 207]
 [143 115 157]
 [ 76 111 161]
 [ 81  91 126]
 [179 140 173]
 [112 100 146]
 [238 229 237]
 [203 161 183]
 [ 84 131 187]
 [ 68  94 156]
 [ 62  52  91]
 [ 84  92 129]
 [132 176 218]
 [ 49 103 161]
 [216 175 192]
 [ 51  55  88]
 [118 186 236]
 [157 122 163]
 [ 37  74 127]
 [ 59  77 117]
 [223 182 196]
 [ 57  39  74]
 [ 76  90 121]
 [140 113 156]
 [124 137 177]
 [ 90  81 115]
 [ 47  28  57]
 [ 58  83 128]
 [118 103 148]
 [ 82 153 218]
 [170 204 233]
 [173 134 169]
 [ 97 106 141]
 [242 209 215]
 [230 191 199]
 [107 155 203]
 [ 92  94 134]
 [ 34  50  91]
 [187 146 175]
 [248 218 220]
 [ 83 140 201]
 [ 74 128 190]
 [ 52  96 151]
 [ 73 114 177]
 [131 108 152]
 [248 253 254]
 [ 88 136 191]
 [ 72  87 117]
 [ 45  63 106]
 [113 189 246]
 [ 58  53  86]
 [ 98 163 218]
 [151 119 159]
 [109 101 